# Application Settings
spring.application.name=vendor-venue-management
server.port=8080

# Spring MVC / Thymeleaf Settings
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Spring Active Profile (Default is H2 in-memory for instant plug-and-play testing; change to 'sqlserver' for SSMS)
spring.profiles.active=sqlserver
